---
name: CI

on: [ push ]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        javaVersion: [ "8", "11", "17" ]
        javaDistribution: [ "adopt", "zulu" ]
    name: Java ${{ matrix.javaVersion }}-${{ matrix.javaDistribution }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.javaDistribution }}
          java-version: ${{ matrix.javaVersion }}
      - uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Test with Maven
        run: mvn test --no-transfer-progress
