---
name: CI

on: [ push ]
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        javaVersion: [ "17", "21" ]
        javaDistribution: [ "adopt", "zulu" ]
    name: Java ${{ matrix.javaVersion }}-${{ matrix.javaDistribution }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.javaDistribution }}
          java-version: ${{ matrix.javaVersion }}
          cache: 'maven'
      - name: Check Code Formatting w/ Spotless
        run: mvn spotless:check --no-transfer-progress
      - name: Test with Maven
        run: mvn test --no-transfer-progress
